apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "name" . }}-nginx
  labels:
    app: {{ template "name" . }}-nginx
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.nginx.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}-nginx
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-nginx
          image: "{{ .Values.nginx.repository }}:{{ .Values.nginx.tag }}"
          imagePullPolicy: {{ .Values.nginx.pullPolicy }}
          ports:
            - containerPort: 80
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
