apiVersion: v1
kind: Service
metadata:
  name: php
  labels:
    app: {{ template "name" . }}-php
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 9000
  selector:
    app: {{ template "name" . }}-php
    release: {{ .Release.Name }}
