<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace Book\Domain\Model\Review\Command;

final class DeleteReview extends \Prooph\Common\Messaging\Command
{
    use \Prooph\Common\Messaging\PayloadTrait;

    public const MESSAGE_NAME = 'Book\Domain\Model\Review\Command\DeleteReview';

    protected $messageName = self::MESSAGE_NAME;

    public function id(): \Book\Domain\Model\Review\ReviewId
    {
        return \Book\Domain\Model\Review\ReviewId::fromString($this->payload['id']);
    }

    public static function with(\Book\Domain\Model\Review\ReviewId $id): self
    {
        return new self([
            'id' => $id->toString(),
        ]);
    }

    protected function setPayload(array $payload): void
    {
        if (!isset($payload['id']) || !\is_string($payload['id'])) {
            throw new \InvalidArgumentException("Key 'id' is missing in payload or is not a string");
        }

        $this->payload = $payload;
    }
}
