sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

install: true

before_script:
  - sudo service postgresql stop
  # wait for postgresql to shutdown
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done

script:
  - docker-compose pull --ignore-pull-failures
  - docker-compose build --pull
  - docker-compose run --no-deps -T php composer validate --no-check-publish
  - docker-compose up -d
  - sleep 20
  - docker-compose exec -T php bin/phpunit
  - docker-compose exec -T php vendor/bin/phpcs
  - docker-compose exec -T php vendor/bin/phpstan analyze
  - docker-compose exec -T php vendor/bin/composer-require-checker
  - docker-compose exec -T php composer req sensiolabs/security-checker
  - docker-compose exec -T php bin/console security:check
  - curl -f http://localhost # Client
  - curl -f http://localhost:81 # Admin
  - curl -f http://localhost:8080 # API
  - curl -f http://localhost:8081 # Varnish
  - curl -fk https://localhost # Client (HTTP/2)
  - curl -fk https://localhost:444 # Admin (HTTP/2)
  - curl -fk https://localhost:8443 # API (HTTP/2)
  - curl -fk https://localhost:8444 # Varnish (HTTP/2)
  - docker-compose exec -T php bin/console app:fixtures:load ./fixtures
  - sleep 5
  - docker ps | grep -q projection_book
  - docker ps | grep -q projection_review

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin "$DOCKER_REGISTRY"

deploy:
  provider: script
  script: docker-compose push
  skip_cleanup: true
  on:
    repo: Lctrs/apiplatform-ddd-cqrs-es-demo
    branch: master
