api_platform:
    version: 1.0.0
    description: |
        This is a demo application of the [API Platform](https://api-platform.com) framework, DDD/CQRS/ES styles!
        [Its source code](https://github.com/Lctrs/apiplatform-ddd-cqrs-es-demo) includes various examples, check it out!
    formats:
        jsonld: ['application/ld+json']
        jsonhal: ['application/hal+json']
        jsonapi: ['application/vnd.api+json']
        json: ['application/json']
        xml: ['application/xml', 'text/xml']
        yaml: ['application/x-yaml']
        csv: ['text/csv']
        html: ['text/html']
    mapping:
        paths:
            - '%kernel.project_dir%/src/Book/Infrastructure/ApiPlatform/Resource'

services:
    book.property_filter:
        parent: api_platform.serializer.property_filter
        tags:
            - api_platform.filter

    review.search_filter.bookId:
        parent: api_platform.doctrine.orm.search_filter
        arguments:
            -
              bookId: exact
        tags:
            - api_platform.filter
                
    App\Core\Infrastructure\ApiPlatform\DataPersister\CommandBusPersister:
        autoconfigure: true
        public: false
        class: App\Core\Infrastructure\ApiPlatform\DataPersister\CommandBusPersister
        arguments:
            - '@messenger.bus.commands'
