api_platform:
    title: Hello API Platform
    version: 1.0.0
    description: |
        This is a demo application of the [API Platform](https://api-platform.com) framework, DDD/CQRS/ES styles!
        [Its source code](https://github.com/Lctrs/apiplatform-ddd-cqrs-es-demo) includes various examples, check it out!
    mapping:
        paths:
            - '%kernel.project_dir%/src/Book/Infrastructure/ApiPlatform/Resource'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]

services:
    book.property_filter:
        parent: api_platform.serializer.property_filter
        tags:
            - api_platform.filter

    review.search_filter.bookId:
        parent: api_platform.doctrine.orm.search_filter
        arguments:
            - bookId: exact
        tags:
            - api_platform.filter

    App\Core\Infrastructure\ApiPlatform\DataPersister\CommandBusPersister:
        autoconfigure: true
        class: App\Core\Infrastructure\ApiPlatform\DataPersister\CommandBusPersister
        arguments:
            - '@command.bus'
