framework:
    messenger:
        buses:
            messenger.bus.commands:
                middleware:
                    - 'App\Core\Infrastructure\MessageBus\CommandBus\Middleware\EventStoreTransactionMiddleware'

services:
    App\Core\Infrastructure\MessageBus\CommandBus\Middleware\EventStoreTransactionMiddleware:
        class: App\Core\Infrastructure\MessageBus\CommandBus\Middleware\EventStoreTransactionMiddleware
        arguments:
            - '@Prooph\EventStore\TransactionalEventStore'
