framework:
    messenger:
        buses:
            messenger.bus.commands:
                middleware:
                    - 'Core\Infrastructure\MessageBus\CommandBus\Middleware\EventStoreTransactionMiddleware'

services:
    Core\Infrastructure\MessageBus\CommandBus\Middleware\EventStoreTransactionMiddleware:
        class: Core\Infrastructure\MessageBus\CommandBus\Middleware\EventStoreTransactionMiddleware
        public: false
        arguments:
            - '@Prooph\EventStore\TransactionalEventStore'
