prooph_service_bus:
    command_buses:
        main_command_bus:
            router:
                type: 'prooph_service_bus.command_bus_router'

services:
    Prooph\EventStoreBusBridge\TransactionManager:
        class: Prooph\EventStoreBusBridge\TransactionManager
        arguments:
            - '@Prooph\EventStore\TransactionalEventStore'
        tags:
            - name: prooph_service_bus.plugin
