<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace Book\Domain\Model\Review;

use Book\Domain\Model\Review\Event\ReviewWasPosted;
use Prooph\EventSourcing\AggregateChanged;
use Prooph\EventSourcing\AggregateRoot;

final class Review extends AggregateRoot
{
    private $id;
    private $body;
    private $rating;
    private $author;

    public static function post(ReviewId $id, ?Body $body, Rating $rating, Author $author)
    {
        $self = new self();

        $self->recordThat(ReviewWasPosted::with($id, $body, $rating, $author));

        return $self;
    }

    public function id(): ReviewId
    {
        return $this->id;
    }

    public function body(): ?Body
    {
        return $this->body;
    }

    public function rating(): Rating
    {
        return $this->rating;
    }

    public function author(): Author
    {
        return $this->author;
    }

    protected function aggregateId(): string
    {
        return $this->id()->toString();
    }

    protected function apply(AggregateChanged $event): void
    {
        switch (\get_class($event)) {
            case ReviewWasPosted::class:
                $this->whenReviewWasPosted($event);
                break;
            default:
                throw new \RuntimeException(sprintf(
                    'Missing event "%s" handler method for aggregate root "%s".',
                    \get_class($event),
                    \get_class($this)
                ));
        }
    }

    private function whenReviewWasPosted(ReviewWasPosted $event): void
    {
        $this->id = $event->id();
        $this->body = $event->body();
        $this->rating = $event->rating();
        $this->author = $event->author();
    }
}
