<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace Book\Domain\Model\Book;

final class BookId
{
    private $uuid;

    private function __construct(\Ramsey\Uuid\UuidInterface $bookId)
    {
        $this->uuid = $bookId;
    }

    public function __toString(): string
    {
        return $this->uuid->toString();
    }

    public static function generate(): self
    {
        return new self(\Ramsey\Uuid\Uuid::uuid4());
    }

    public static function fromString(string $bookId): self
    {
        return new self(\Ramsey\Uuid\Uuid::fromString($bookId));
    }

    public function toString(): string
    {
        return $this->uuid->toString();
    }

    public function equals(self $other): bool
    {
        return $this->uuid->equals($other->uuid);
    }
}
