fidry_alice_data_fixtures:
    db_drivers:
        doctrine_orm: false

services:
    _defaults:
        autoconfigure: true
        public: false

    App\Core\Infrastructure\Fixtures\Cli\LoadDataFixturesCommand:
        class: App\Core\Infrastructure\Fixtures\Cli\LoadDataFixturesCommand
        arguments:
            - '@Fidry\AliceDataFixtures\LoaderInterface'

    App\Core\Infrastructure\Fixtures\Persistence\CommandBusPersister:
        class: App\Core\Infrastructure\Fixtures\Persistence\CommandBusPersister
        arguments:
            - '@messenger.bus.commands'

    Fidry\AliceDataFixtures\LoaderInterface:
        class: Fidry\AliceDataFixtures\Loader\PersisterLoader
        arguments:
            - '@fidry_alice_data_fixtures.loader.simple'
            - '@App\Core\Infrastructure\Fixtures\Persistence\CommandBusPersister'
            - '@?logger'
