# https://dependabot.com/docs/config-file/

version: 1

update_configs:
  - default_assignees:
      - "Lctrs"
    default_labels:
      - "dependency"
    default_reviewers:
      - "Lctrs"
    directory: "/"
    package_manager: "github_actions"
    update_schedule: "daily"

  - automerged_updates:
      - match:
          dependency_type: "all"
    default_labels:
      - "dependency"
    default_reviewers:
      - "Lctrs"
    directory: "/admin"
    package_manager: "javascript"
    update_schedule: "live"
    version_requirement_updates: "increase_versions"

  - automerged_updates:
      - match:
          dependency_type: "development"
      - match:
          dependency_type: "production"
          update_type: "semver:patch"
    default_assignees:
      - "Lctrs"
    default_labels:
      - "dependency"
    default_reviewers:
      - "Lctrs"
    directory: "/api"
    package_manager: "php:composer"
    update_schedule: "live"
    version_requirement_updates: "increase_versions"
    ignored_updates:
      - match:
          dependency_name: "symfony/*"

  - automerged_updates:
      - match:
          dependency_type: "all"
    default_assignees:
      - "Lctrs"
    default_labels:
      - "dependency"
    default_reviewers:
      - "Lctrs"
    directory: "/client"
    package_manager: "javascript"
    update_schedule: "live"
    version_requirement_updates: "increase_versions"
