# https://dependabot.com/docs/config-file/

version: 1

update_configs:
  - commit_message:
      include_scope: true
      prefix: "Build"
    default_labels:
      - "dependency"
    directory: "/admin"
    package_manager: "javascript"
    update_schedule: "live"
    version_requirement_updates: "increase_versions"

  - commit_message:
      include_scope: true
      prefix: "Build"
    default_labels:
      - "dependency"
    directory: "/api"
    package_manager: "php:composer"
    update_schedule: "live"
    version_requirement_updates: "increase_versions"
    ignored_updates:
      - match:
          dependency_name: "symfony/asset"
          version_requirement: ">= 5.2.0"
      - match:
          dependency_name: "symfony/config"
          version_requirement: ">= 5.2.0"
      - match:
          dependency_name: "symfony/console"
          version_requirement: ">= 5.2.0"
      - match:
          dependency_name: "symfony/dependency-injection"
          version_requirement: ">= 5.2.0"
      - match:
          dependency_name: "symfony/doctrine-bridge"
          version_requirement: ">= 5.2.0"
      - match:
          dependency_name: "symfony/dotenv"
          version_requirement: ">= 5.2.0"
      - match:
          dependency_name: "symfony/framework-bundle"
          version_requirement: ">= 5.2.0"
      - match:
          dependency_name: "symfony/http-client"
          version_requirement: ">= 5.2.0"
      - match:
          dependency_name: "symfony/http-kernel"
          version_requirement: ">= 5.2.0"
      - match:
          dependency_name: "symfony/messenger"
          version_requirement: ">= 5.2.0"
      - match:
          dependency_name: "symfony/routing"
          version_requirement: ">= 5.2.0"
      - match:
          dependency_name: "symfony/serializer"
          version_requirement: ">= 5.2.0"
      - match:
          dependency_name: "symfony/twig-bundle"
          version_requirement: ">= 5.2.0"
      - match:
          dependency_name: "symfony/validator"
          version_requirement: ">= 5.2.0"
      - match:
          dependency_name: "symfony/yaml"
          version_requirement: ">= 5.2.0"
      - match:
          dependency_name: "symfony/finder"
          version_requirement: ">= 5.2.0"
      - match:
          dependency_name: "symfony/phpunit-bridge"
          version_requirement: ">= 5.2.0"
      - match:
          dependency_name: "symfony/stopwatch"
          version_requirement: ">= 5.2.0"
      - match:
          dependency_name: "symfony/web-profiler-bundle"
          version_requirement: ">= 5.2.0"

  - commit_message:
      include_scope: true
      prefix: "Build"
    default_labels:
      - "dependency"
    directory: "/client"
    package_manager: "javascript"
    update_schedule: "live"
    version_requirement_updates: "increase_versions"
