# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    _instanceof:
        App\Core\Domain\DomainEvent:
            tags: ['app.domain_event']
    App\Book\Domain\Model\Book\Event\BookWasCreated:
        class: App\Book\Domain\Model\Book\Event\BookWasCreated
    App\Book\Domain\Model\Review\Event\:
        class: App\Book\Domain\Model\Book\Event\BookWasDeleted
    App\Book\Domain\Model\Review\Event\ReviewWasDeleted:
        class: App\Book\Domain\Model\Review\Event\ReviewWasDeleted
    App\Book\Domain\Model\Review\Event\ReviewWasPosted:
        class: App\Book\Domain\Model\Review\Event\ReviewWasPosted

    App\Core\Domain\EventStore:
        alias: App\Core\Infrastructure\Persistence\Prooph\EventStore
    App\Core\Infrastructure\Persistence\Prooph\EventStore:
        class: App\Core\Infrastructure\Persistence\Prooph\EventStore
        arguments:
            - '@Prooph\EventStore\EventStore'
            - '@App\Core\Infrastructure\Persistence\Prooph\Internal\DomainEventTransformer'
    App\Core\Infrastructure\Persistence\Prooph\Internal\DomainEventTransformer:
        class: App\Core\Infrastructure\Persistence\Prooph\Internal\DomainEventTransformer
        arguments:
            - []
            
    App\Core\Infrastructure\Cli\CreateEventStreamCommand:
        class: App\Core\Infrastructure\Cli\CreateEventStreamCommand
        arguments:
            - '@Prooph\EventStore\EventStore'

    App\Book\Infrastructure\Persistence\EventStore\EventStoreBookList:
        class: App\Book\Infrastructure\Persistence\EventStore\EventStoreBookList
        arguments:
            - '@App\Core\Domain\EventStore'
    App\Book\Domain\Model\Book\BookList:
        alias: App\Book\Infrastructure\Persistence\EventStore\EventStoreBookList
    App\Book\Domain\Model\Book\Handler\CreateBookHandler:
        class: App\Book\Domain\Model\Book\Handler\CreateBookHandler
        arguments:
            - '@App\Book\Domain\Model\Book\BookList'
        tags:
            - messenger.message_handler
    App\Book\Domain\Model\Book\Handler\DeleteBookHandler:
        class: App\Book\Domain\Model\Book\Handler\DeleteBookHandler
        arguments:
            - '@App\Book\Domain\Model\Book\BookList'
        tags:
            - messenger.message_handler
    App\Book\Infrastructure\Projection\BookProjection: ~
    App\Book\Infrastructure\Projection\Doctrine\Orm\BookReadModel:
        class: App\Book\Infrastructure\Projection\Doctrine\Orm\BookReadModel
        arguments:
            - '@doctrine.orm.default_entity_manager'

    App\Book\Infrastructure\Persistence\EventStore\EventStoreReviewList:
        class: App\Book\Infrastructure\Persistence\EventStore\EventStoreReviewList
        arguments:
            - '@App\Core\Domain\EventStore'
    App\Book\Domain\Model\Review\ReviewList:
        alias: App\Book\Infrastructure\Persistence\EventStore\EventStoreReviewList
    App\Book\Domain\Model\Review\Handler\PostReviewHandler:
        class: App\Book\Domain\Model\Review\Handler\PostReviewHandler
        arguments:
            - '@App\Book\Domain\Model\Book\BookList'
            - '@App\Book\Domain\Model\Review\ReviewList'
        tags:
            - messenger.message_handler
    App\Book\Domain\Model\Review\Handler\DeleteReviewHandler:
        class: App\Book\Domain\Model\Review\Handler\DeleteReviewHandler
        arguments:
            - '@App\Book\Domain\Model\Review\ReviewList'
        tags:
            - messenger.message_handler
    App\Book\Infrastructure\Projection\ReviewProjection: ~
    App\Book\Infrastructure\Projection\Doctrine\Orm\ReviewReadModel:
        class: App\Book\Infrastructure\Projection\Doctrine\Orm\ReviewReadModel
        arguments:
            - '@doctrine.orm.default_entity_manager'
